### PR TITLE
Update abstractions for docker protos items

### PR DESCRIPTION
**Pull request by ssalinas**
We have abstractions that mirror the mesos Protos fields for some things but not others, this will complete those for docker items

/cc @tpetr

### CODE REVIEW

**Comment by ssalinas** [comment]
FYI, going to still add extra constructors in so previous client versions will still work.

**Comment by tpetr** [comment]
sounds good, let's deprecate those the proto-based constructors and remove in a future version

**Comment by ssalinas** [comment]
Ran into a small snag make the old proto-based constructors worked. Since two were Optional<> 's I ran into 'method with same erasure' issues trying to implement the second constructor. Let me know if can think of a better workaround for the same erasure issue

**Comment by tpetr** [comment]
@ssalinas this good to merge?

**Comment by ssalinas** [comment]
Yep

**Pull request merged**
