### PR TITLE
Highlight decomissioning history states

### PR DESCRIPTION
**Pull request by kwm4385**

### CODE REVIEW

**Comment by tpetr** [comment]
can you include an example screenshot?

**Comment by kwm4385** [comment]
image

**Comment by wsorenson** [comment]
Should we have some kind of message bar that floats in at the top?

**Comment by kwm4385** [comment]
That could also work. Would it be in place of the current highlighting or in combination?

**Comment by kwm4385** [comment]
Rolled into task alerts PR, closing this one in favor of that.

https://github.com/HubSpot/Singularity/pull/721

**Pull request closed without merging**
