### PR TITLE
add container fields, other updates to validator

### PR DESCRIPTION
**Pull request by ssalinas**
@wsorenson @stevenschlansker 
fixes to help avoid the reason for #668

### CODE REVIEW

**Comment by stevenschlansker** [comment]
Cool.  I'm still of the opinion that since we use `Optional<T>` pervasively in the domain objects, any non-Optional field should be assumed to be `@NonNull` and verified as such.  End users will expect that behavior.  I am neither specifically pushing for my PR nor against this PR, just trying to make sure my "philosophy" here is consistent with yours.

**Comment by ssalinas** [comment]
Yes, definitely agree with the philosophy there. We are already doing our other checks for other invalid data or combinations of data in the validators (e.g. deploy id or not having a base path for a load balanced service), thought it made sense to have all of our defense against bad data in the same place

**Comment by stevenschlansker** [comment]
:+1:

**Comment by jeffbyrnes** [comment]
Adding some bits here after a convo in EverTrue’s #mesos Slack channel.

If a Request is `loadBalanced`, but is sent a Deploy without a `loadBalancerGroup`, the deploy will fail, with the load balancer response from Baragon being buried in the Deploy JSON.

**Pull request merged**
