### PR TITLE
Redux API auto refresh

### PR DESCRIPTION
**Pull request by wolfd**
Lifecycle hooks:
```
componentDidMount() {
  this.props.refresh();
}

componentWillUnmount() {
  this.props.cancelRefresh();
}
```

`mapDispatchToProps`:
```
refresh: () => dispatch(RefreshActions.BeginAutoRefresh('RequestDetailPage', [
  FetchRequest.trigger(ownProps.requestId),
  FetchActiveTasksForRequest.trigger(ownProps.requestId),
  FetchTaskCleanups.trigger()
], 10000)),
cancelRefresh: () => dispatch(
  RefreshActions.CancelAutoRefresh('RequestDetailPage')
)
```

### CODE REVIEW

**Comment by tpetr** [comment]
do you mean `mapDispatchToProps` for the 2nd bit?

**Comment by tpetr** [comment]
why not create an `autoRefresh()` decorator a la redux-form to cut down on copypasta?

**Comment by wolfd** [comment]
The decorator is a good idea, but I think we should hold off on it for now. It's not that hard to do it this way, and we'll have a better idea of how to move forward with a decorator once we use this a few times.

**Comment by tpetr** [comment]
LGTM once we remove the action data from the store. 👍 for circling back on the decorator.

**Pull request merged**
