### PR TITLE
Mesos 0.22.1 (WIP)

### PR DESCRIPTION
**Pull request by ssalinas**
Still working on this, but it's a start. This will address #592 and #584 once I get the UI components in place

Still TODO:
- [ ] Add task labels into tests to be sure they work (bonus: visible/searchable in the UI)
- [ ] Docker parameters/forcePullImage in ui
- [ ] Test it all

/cc @tpetr

### CODE REVIEW

**Comment by ssalinas** [comment]
Still working on this, currently running into an issue where Singularity is never getting TASK_FINISHED updates in some cases

**Comment by wsorenson** [comment]
Why bother with vagrant?

**Comment by ssalinas** [comment]
Not going to bother with vagrant anymore, forgot to update the checklist, thanks

**Comment by ssalinas** [comment]
will come back to this and revisit differently, closing for now

**Pull request closed without merging**
