### PR TITLE
Some ui fixes

### LINKED ISSUE #317: (ui) On New Request page, Instances form field and label are too narrow (Firefox Only)
Actually the whole data entry portion of the page seems to be to have its width incorrectly constrained.

### LINKED ISSUE #321: (ui) The "form" tag on the "New deploy" page has no "action" property
As a result it is doing a GET request to the API instead of the desired POST.

### LINKED ISSUE #945: No easy way to pass multiple args to ON_DEMAND jobs from the UI
When I've setup a docker ON_DEMAND job and tried passing in args from the UI, I see that the command line input is not split on whitespace.  Here's the relevant bits of doing a `docker inspect` after the fact on a container that was launched by singularity in this way:

```
$ sudo docker inspect 54f8c357cd4f
[
    {
        "Id": "54f8c357cd4fa214fefae11bbf27ab3b5851c49861f2fa3fb280ed716100d613",
        "Created": "2016-03-11T19:34:39.312828156Z",
        "Path": "/usr/bin/node",
        "Args": [
            "/app/lib/echo.js hi"
        ],
```

The command line I passed in the UI was: `/app/lib/echo.js hi`.  the --entrypoint I specified for the container was `/usr/bin/node`.  What I was hoping for was that the command line input I specified in the singularity UI would be passed as separate args (split on whitespace).  It seems like the optional command line input you specify in the UI should either a) split that input on whitespace or b) the UI should allow you to specify multiple arguments (one textfield for each).

fwiw - There is a similar (multiple textfields) capability over in the ENV var setup for new container deploys.

### PR DESCRIPTION
**Pull request by ssalinas**
- fix a missing argument for handling an event /fixes #321
- allow mutliple command line inputs and clean up the code around keeping history/rerunning /fixes #945 

/cc @dtabwhite @eherot

### CODE REVIEW

**Comment by ssalinas** [comment]
WIP => when done also /fixes #897

**Comment by ssalinas** [comment]
Finished changes now, overall:
/fixes #897
/fixes #321 
/fixes #317 
/fixes #945

**Comment by bradjorgensen** [comment]
Does this pull request add support for properties like requiredSlaveAttributes on the request create/edit forms?

**Comment by ssalinas** [comment]
@bradjorgensen it is not in this PR, we can add it into another one

**Pull request merged**
