### PR TITLE
Change allocated cpu units to floats in the json object

### PR DESCRIPTION
**Pull request by kwm4385**
/cc @tpetr

### CODE REVIEW

**Comment by tpetr** [comment]
could you use `double` to match the original protobuf? https://github.com/apache/mesos/blob/0.23.0/include/mesos/mesos.proto#L555-L650

**Comment by kwm4385** [comment]
Can do

**Comment by tpetr** [comment]
@kwm4385 after looking closer, those two fields are supposed to be `long`, not `double`, so I dont think they're causing the resources UI bug. made appropriate changes in commit above.

**Comment by kwm4385** [comment]
Does this solve the original issue?

**Pull request merged**
