### PR TITLE
Admin only components pages

### PR DESCRIPTION
**Pull request by Calvinp**
This implements admin restrictions in the UI in a slightly different way.
Instead of implementing the restriction in the router, it's implemented in the view. Instead of popping up a vex dialog, a permission denied page will be shown when trying to access a page you don't have rights to view.

### CODE REVIEW

**Comment by ssalinas** [comment]
I definitely like this implementation better, @tpetr you agree?

**Comment by zdhickman** [comment]
The `AdminOnly` wrapper component is a great idea.

Do you guys plan to add any other admin-only React pages in the future? If so, what do you think about adding an `AdminOnlyPage` component that makes use of `AdminOnly`? It would be inherited by this page and could be inherited by any other React page implemented in SingularityUI in the future. That would save you from adding some boilerplate on every page.

(maybe you could also make a base `Page` component. `TaskSearch` extends `AdminOnlyPage` extends `Page`, if you have shared structure across the React pages in Singularity)

**Comment by Calvinp** [comment]
I do like the concept of an AdminOnlyPage (and Page) component.
Task Search in particular is not _always_ admin only - only global task search is admin only. That's the only problem I can see that would need to be worked around to implement AdminOnlyPage.

**Comment by ssalinas** [comment]
If we add more, it's a once in a while thing (e.g. we are adding a webhooks page, but no other plans after that). However, we may eventually convert the previous admin pages to react at some point

**Comment by zdhickman** [comment]
:+1: might be extra work without much gain, then.

**Comment by ssalinas** [comment]
We are going to leave this one be for now, since the no-user bug was fixed, closing

**Pull request closed without merging**
