### PR TITLE
Add logging output to S3 artifiact details when downloading

### PR DESCRIPTION
**Pull request by mgreene**

### CODE REVIEW

**Comment by wsorenson** [comment]
I might change this to be at the top of the method:

<code>
 private void downloadThrows(final S3Artifact s3Artifact, final Path downloadTo) throws Exception {

    log.info("Downloading {}", s3Artifact);

</code>

Mark does that make sense? I can make the change myself or you can update this.

**Comment by mgreene** [comment]
@wsorenson :+1:

**Comment by wsorenson** [comment]
Build failed b/c it enforces 2 spaces instead of tabs :)

**Comment by wsorenson** [comment]
https://github.com/HubSpot/Singularity/commit/1c8ba4c7177e317f753265a5647a57e14f9e36e0

**Pull request closed without merging**
