### PR TITLE
Use direct string matching with glob patterns instead of fuzzy matching

### PR DESCRIPTION
**Pull request by Calvinp**
Gets rid of fuzzy matching on the requests page, using exact string matching instead (or glob matching if the user specifies a glob pattern).

TODO:
- [x] Implement glob matching on the tasks page too.
- [x] Make it clear to the user that glob matching is a possibility.
- [ ] Implement glob matching with highlighting on global search (Maybe).

Note that matches at the start of a requestId are prioritized over matches anywhere else (including at the start of the user field).

cc @tpetr @kwm4385 @wolfd

### CODE REVIEW

**Comment by Calvinp** [comment]
I added a tooltip with a click overlay trigger to explain to the user that they can use `*` if they need wildcard matching:
screenshot 2016-08-15 16 55 24

**Comment by kwm4385** [comment]
I wouldn't be opposed to having the tip in the placeholder, but I'm not sold either way.

**Comment by tpetr** [comment]
I'm not hugely wild about that approach because it seems hard for people to discover, and then once they know about it, it'll be an annoyance whenever it shows up. What do you guys think about a ? icon somewhere nearby that either shows a tooltip or pops open a modal that explains how filtering works? That way people can find it easily, and only engage it when they need it.

**Comment by Calvinp** [comment]
I like that idea better than what I have now.

**Comment by Calvinp** [comment]
Once user settings are fully implemented, we could even show a modal the first time a user goes to the requests or tasks page - then when they close the modal we send an API call to never show it again.

That might have some pitfalls, but at least we can start thinking about things like that now.

**Comment by Calvinp** [comment]
This is what I have now:
screenshot 2016-08-16 09 12 29
screenshot 2016-08-16 09 12 39

I would not be opposed to moving the `?` button if someone has a better idea of where to put it.

**Comment by kwm4385** [comment]
Maybe have it inline like the clear button? I'd put it right before it.

**Comment by tpetr** [comment]
- Put it on the same row as the request type toggles. Not sure if left or right aligned would look better.
- "Did you know?" doesn't really match the tone of the UI. I'd suggest titling it "Filtering requests" or not having a title at all.
- We should include more information about how the search works. If we still have fuzzy matching enabled, explain that, etc...

**Comment by Calvinp** [comment]
Button on the left:
screenshot 2016-08-16 09 25 47

Button centered:
screenshot 2016-08-16 09 25 27

Button on the right:
screenshot 2016-08-16 09 32 25


I personally like the centered version the best.

New modal:
screenshot 2016-08-16 09 36 28

**Comment by Calvinp** [comment]
Added it to the tasks page too:
screenshot 2016-08-16 11 11 40


screenshot 2016-08-16 11 10 23

**Comment by Calvinp** [comment]
Closed in favor of #1228

**Pull request closed without merging**
