### PR TITLE
Remove task credit ui calls, no longer used

### PR DESCRIPTION
**Pull request by ssalinas**
Missed a few pieces when removing this. The backend and visual components were removed, forgot the background refresh piece.

### CODE REVIEW

**Comment by benheng** [comment]
There are still references to task credits in the following files:
- [ ] Docs/reference/api.md
- [ ] Docs/reference/apidocs/api-disasters.md
- [ ] Docs/reference/apidocs/models.md
- [ ] SingularityBase/src/main/java/com/hubspot/singularity/SingularityTaskCredits.java

**Comment by ssalinas** [comment]
the docs ones are all autogenerated and we commit them at release time. I'll remove the model from base though

**Comment by benheng** [comment]
🚢

**Comment by benheng** [comment]
🚢

**Comment by pschoenfelder** [comment]
🚢

**Pull request merged**
