### PR TITLE
make files table in task view sortable

### PR DESCRIPTION
**Pull request by ssalinas**

### CODE REVIEW

**Comment by kwm4385** [comment]
@ssalinas Just tweaked an attr so we don't sort on the last column.

**Comment by ssalinas** [comment]
Cool, thanks

**Comment by tpetr** [comment]
- Seeing some weirdness when sorting by Size:
  screen shot 2015-12-15 at 11 45 47 am
  screen shot 2015-12-15 at 11 47 25 am
- Task refresh blows away the sort setting

**Comment by ssalinas** [comment]
@tpetr believe I have fixed the odd sorting now, we had some odd stuff going on with data-value which is used by sortable. Probably due to an older way of doing sorting. Still need to fix the task refresh piece

**Comment by ssalinas** [comment]
Actually, sort clearing on task refresh might be part of a larger problem, looks like sorts do that on all of our pages, not just here

**Comment by tpetr** [comment]
LGTM -- let's revisit the sort clearing on refresh in a separate PR

**Pull request merged**
