### PR TITLE
Fix machines pages linting errors

### PR DESCRIPTION
**Pull request by Calvinp**
Fixes linting errors in Racks and Slaves views and React pages. The controllers and Actions didn't have linting errors.

Unfortunately the diff isn't pretty because indentation fixes took over.

### CODE REVIEW

**Comment by Calvinp** [comment]
The racks and slaves pages have a problem (not caused by the changes in this PR, but this could be a good place to fix it). The buttons to freeze/remove/decommission/reactivate slaves and racks are all broken. Each and every one of them. They throw an error `Uncaught TypeError: slaveModel.promptDecommission is not a function`.

**Comment by tpetr** [comment]
LGTM

**Comment by Calvinp** [comment]
So I'll fix the buttons in a different PR then.

**Comment by tpetr** [comment]
either this PR or a separate one -- whichever makes the most sense to you. thanks!

**Comment by Calvinp** [comment]
Thinking about it, it might be a large change. So go ahead and merge this PR, and I'll open a new one for that once it's implemented.

**Pull request merged**
