### PR TITLE
bump curator version to 2.8.0

### PR DESCRIPTION
**Pull request by ssalinas**
Should fix the issue we are seeing in #620 

@stevenschlansker @wsorenson

### CODE REVIEW

**Comment by stevenschlansker** [comment]
:+1:

**Comment by jhaber** [comment]
Probably want to bump it [here](https://github.com/HubSpot/basepom/blob/master/pom.xml#L56), trying to keep all of our open-source stuff on the same versions to reduce conflicts

**Comment by ssalinas** [comment]
Going to bump this in the basepom as suggested by @jhaber, next build of Singularity should then have the new version. Closing this pr

**Comment by tpetr** [comment]
https://github.com/HubSpot/basepom/pull/1

**Comment by tpetr** [comment]
also https://github.com/HubSpot/Singularity/pull/652

**Pull request closed without merging**
