### PR TITLE
Adding more decommission states

### PR DESCRIPTION
**Pull request by wsorenson**
- Addressing #354 
- Cleaning up decommission code
- Adding decommission tests

### CODE REVIEW

**Comment by tpetr** [comment]
I was testing the UI by decommissioning a slave with no running tasks, and it never reached the `DECOMISSIONED` state -- seems to hang in `DECOMISSIONING` indefinitely for me (using a fresh vagrant box)

**Comment by wsorenson** [comment]
Good catch - we don't have a test / code for that!

**Comment by ssalinas** [comment]
@wsorenson fixed merge conflicts and removed all the old 1 'm' spellings in the ui stuff

**Comment by ssalinas** [comment]
@wsorenson fixed the user not showing up for Activated by/Decom by

**Pull request merged**
