### PR TITLE
Skip offers with null id

### PR DESCRIPTION
**Pull request by ssalinas**
Not sure why we've started getting these still, but a fix until we figure out the source

### CODE REVIEW

**Comment by sjeropkipruto** [comment]
🚢

**Comment by baconmania** [comment]
🚢

**Comment by baconmania** [comment]
🚢

**Comment by ssalinas** [comment]
🚢

**Comment by ssalinas** [comment]
🚢

**Comment by ssalinas** [comment]
@baconmania , gonna merge this one and we can continue debugging odd offer things in a new PR

**Pull request merged**
