### PR TITLE
Reorganize task label colors

### PR DESCRIPTION
**Pull request by Calvinp**
Reorganizes task label colors such that:
- Task States that don't require action, but aren't serving requests are `info` or `primary` (different shades of blue that distinguish similar but different states)
- Task States that are currently serving requests are `success` (green)
- Task States that indicate a failure and may require attention are `danger` (red)
- Task States that indicate either a small problem or no problem, but aren't a task-initiated completion, are `warning` (orange)
- Task States that are unknown to the UI are `default` (black)

cc @ssalinas @tpetr @markhazlewood @wolfd @kwm4385 
This PR should not be merged until all of those people have a chance to look at it and share their opinions because it is a fairly large change in the look of tasks (even if the code is small).
The original motivation was to distinguish tasks that are currently serving requests from ones that aren't, but then grew to group similar states as a whole.

Screenshots:
screenshot 2016-07-20 10 42 06
screenshot 2016-07-20 11 08 45
screenshot 2016-07-20 14 20 20
screenshot 2016-07-20 14 20 58

### CODE REVIEW

**Comment by ssalinas** [comment]
A few things:
- `TASK_KILLED` should not be an orange. Tasks will end up in this state if they are asked to shut down and do so gracefully. The orange signifies to me that something is still wrong/might be wrong. I'd argue for keeping the current grey for killed
- I'm unsure about `TASK_CLEANING`, it'd make more sense to keep it green if we had another state to transition to when a task was in the process of being killed, and no longer serving requests (i.e. making better use of `TASK_KILLING`, but currently a cleaning task (for however short a time) may not always be serving requests (in the case of a web service). Could be convinced otherwise on this, but wanted to state the concern

**Comment by kwm4385** [comment]
This might be easier to reason about if we make a tree of the task lifecycle chronologically and see if it makes sense to assign colors by region.

**Comment by markhazlewood** [comment]
Approve of these changes and agree w/ @ssalinas and @kwm4385 on all counts.

**Comment by Calvinp** [comment]
Here's the tree as best I understand it. Sorry it's not pretty, I'm not Mark :p There are probably a bunch more arrows going to `Lost`, `Failed`, and `Lost While Down`, but this should be the general idea.

screenshot 2016-07-20 14 56 45

The reason `TASK_CLEANING` was green is because I thought it was always serving requests. Remember the original problem was that `TASK_CLEANING` being orange was worrying developers, who thought there was nothing serving their requests for a short period. What color would you suggest?
Another possibility would be to redesign the request detail page entirely to show tasks that are serving requests in their own table. Then there could be at most one state of each color in each table (except the completed tasks table, since there are a bunch of bad states).

**Comment by kwm4385** [comment]
taskstates

My reasoning:
Green: Task is running and guaranteed to be serving requests at this time
Light/dark blue: Task may not be serving requests, but the state that it's in is expected and no action is needed
Red: Something went wrong and you may want to investigate
Orange: Something is wrong but action might not be required on your part
Grey: Task is waiting/not relevent now

**Comment by Calvinp** [comment]
While I agree with most of that chart, it still doesn't solve the anxiety that occurs when all tasks are in `cleaning` or `starting` during certain kinds of bounce.

**Comment by kwm4385** [comment]
I suppose the only answer to that would be to make `cleaning` and `running` the same color.

**Comment by Calvinp** [comment]
Then we're back to the problem that @ssalinas had which is that `cleaning` isn't guaranteed to be serving requests...
We're kind of stuck between a rock and a hard place here.

**Comment by kwm4385** [comment]
Yeah I think its either we solve that anxiety by telling people something that isn't _quite_ true, or be absolutely accurate in our labeling.

**Comment by Calvinp** [comment]
Maybe we could use dark blue for `cleaning` and light blue for `finished`. Then add a note of some sort (maybe an alert) that cleaning tasks may still be accepting requests.

**Comment by Calvinp** [comment]
Closing this to avoid making huge UX changes in the `decaf` branch.
Once `deacf` is merged we will circle back to this.

**Pull request closed without merging**
