### PR TITLE
Typo: "Settingss" -> "Settings" on the Deploy form

### PR DESCRIPTION
**Pull request by demobox**

### CODE REVIEW

**Comment by demobox** [comment]
Failures look unrelated to the change?
```
The command "wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip" failed and exited with 8 during .
```

/cc @ssalinas

**Comment by ssalinas** [comment]
Yeah, travis was having a rough time earlier. Should be gtg

**Comment by ssalinas** [comment]
@wolfd @kwm4385 just fyi on this one in case it causes any merge conflicts for your bigger recent UI changes

**Comment by demobox** [comment]
> ssalinas merged commit

Thanks, @ssalinas!

**Pull request merged**
